### ISSUE TITLE
what is this repo about ? 

### ISSUE THREAD

**Issue by navotera** [openjournalteam/Core#37]
rename aja sesuai dengan fungsi utama misalnya OJT Hosting Core System atau apa ...

**Comment by thisnugroho** [comment]
Untuk namanya sudah pas aja sepertinya pa, ini output translate framework CI yang dulu ke laravel,isinya seperti:

1. User Management
2. Authentication
3. Menu Management

**Comment by navotera** [comment]
Bisa ditambahkan di readme : 

#About 
....

##Features
